[package]
name = "pre-commit-cargo"
version = "0.4.0"
license = "MIT"
repository = "https://github.com/AndrejOrsula/pre-commit-cargo"
edition = "2024"

[[bin]]
name = "cargo-update-shim"
path = "src/cargo_update_shim.rs"
